<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="CourseArchive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="search">
			<sakai:tool_bar>
				<h:inputText value="#{CourseArchiveBean.searchQuery}"/>
				<h:commandButton value="#{msgs.search}" action="#{CourseArchiveBean.processActionSearch}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="items">
				<sakai:view_title value="#{msgs.items_list_page_title}"/>

				<sakai:messages />

				<h:dataTable
					id="itemlist"
					value="#{CourseArchiveBean.items}"
					var="entry"
					columnClasses="checkCol,termCol,codeCol,nameCol,instructorCol,enrollmentCol,publicCol,dateCol"
					headerClass="headerAlignment"
					styleClass="listHier">

					<h:column>
						<f:facet name="header">
							<h:outputText value=""/>
						</f:facet>
						<h:selectBooleanCheckbox id="itemSelect" value="#{entry.selected}" rendered="#{entry.canDelete}"/>
						<h:outputText value="" rendered="#{not entry.canDelete}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Term"/>
						</f:facet>
						<h:outputText value="#{entry.item.term}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Code"/>
						</f:facet>
						<h:commandLink id="showlink" action="#{CourseArchiveBean.processActionShow}">
							<h:outputText value="#{entry.item.code}"/>
						</h:commandLink>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Name"/>
						</f:facet>
						<h:outputText value="#{entry.item.name}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Primary Instructor"/>
						</f:facet>
						<h:outputText value="#{entry.item.primaryInstructor}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Enrollment"/>
						</f:facet>
						<h:outputText value="#{entry.item.enrollment}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Public?"/>
						</f:facet>
						<h:outputText value="#{entry.item.public}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.items_list_date}"/>
						</f:facet>
						<h:outputText value="#{entry.item.dateCreated}">
							<f:convertDateTime type="both" dateStyle="medium" timeStyle="short"/>
						</h:outputText>
					</h:column>

				</h:dataTable>

				<sakai:button_bar>
					<sakai:button_bar_item id="deleteItem" action="#{CourseArchiveBean.processActionDelete}" value="#{msgs.project_items_delete}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
