<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}"/>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionShowRoster}" value="Show Class Roster"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form>
				<sakai:view_title value="#{CourseArchiveBean.itemCode}-#{CourseArchiveBean.itemTerm}"/>

				<sakai:panel_edit>
					<h:outputText value="Code"/>
					<h:outputText value="#{CourseArchiveBean.itemCode}"/>

					<h:outputText value="Term"/>
					<h:outputText value="#{CourseArchiveBean.itemTerm}"/>

					<h:outputText value="Name"/>
					<h:outputText value="#{CourseArchiveBean.itemName}"/>

					<h:outputText value="Primary Instructor"/>
					<h:outputText value="#{CourseArchiveBean.itemPrimaryInstructor}"/>

					<h:outputText value="Other Instructors"/>
					<h:outputText value="#{CourseArchiveBean.itemOtherInstructors}" escape="false">
						<f:converter converterId="NewlineConverter"/>
					</h:outputText>

					<h:outputText value="Assistants"/>
					<h:outputText value="#{CourseArchiveBean.itemAssistants}" escape="false">
						<f:converter converterId="NewlineConverter"/>
					</h:outputText>

					<h:outputText value="Enrollment"/>
					<h:outputText value="#{CourseArchiveBean.itemEnrollment} "/>

					<h:outputText value="Comments"/>
					<h:outputText value="#{CourseArchiveBean.itemComments}"/>

					<h:outputText value="Public?"/>
					<h:outputText value="#{CourseArchiveBean.itemPublic}"/>
				</sakai:panel_edit>

				<h:dataTable
					value="#{CourseArchiveBean.itemAssignments}"
					var="assignment"
					headerClass="headerAlignment"
					styleClass="listHier">
					<h:column>
						<f:facet name="header">
							<h:outputText value="Title"/>
						</f:facet>
						<h:outputText value="#{assignment.title}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Max. Points"/>
						</f:facet>
						<h:outputText value="#{assignment.points}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Mean Grade"/>
						</f:facet>
						<h:outputText value="#{assignment.meanGrade}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Due Date"/>
						</f:facet>
						<h:outputText value="#{assignment.dueDate}">
							<f:convertDateTime type="both" dateStyle="medium" timeStyle="short"/>
						</h:outputText>
					</h:column>

				</h:dataTable>

				<sakai:button_bar>
					<h:commandButton value="#{msgs.edit_button}" action="#{CourseArchiveBean.processActionUpdate}" rendered="#{CourseArchiveBean.itemCanEdit}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
