<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form>
				<sakai:view_title value="#{CourseArchiveBean.itemCode}"/>

				<sakai:messages />

				<sakai:panel_edit>
					<h:outputText value="Term"/>
					<h:outputText value="#{CourseArchiveBean.itemTerm}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Code"/>
					<h:outputText value="#{CourseArchiveBean.itemCode}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Name"/>
					<h:outputText value="#{CourseArchiveBean.itemName}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Primary Instructor"/>
					<h:outputText value="#{CourseArchiveBean.itemPrimaryInstructor}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Other Instructors"/>
					<h:outputText value="#{CourseArchiveBean.itemOtherInstructors}" escape="false">
						<f:converter converterId="NewlineConverter"/>
					</h:outputText>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Assistants"/>
					<h:outputText value="#{CourseArchiveBean.itemAssistants}" escape="false">
						<f:converter converterId="NewlineConverter"/>
					</h:outputText>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Enrollment"/>
					<h:outputText value="#{CourseArchiveBean.itemEnrollment}"/>
				</sakai:panel_edit>

				<sakai:button_bar>
					<h:commandButton value="#{msgs.edit_button}" action="#{CourseArchiveBean.processActionUpdate}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
