<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.list_items}" />
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form>
				<sakai:view_title value="Select Syllabi to Archive"/>

				<sakai:messages />

				<h:dataTable
					value="#{CourseArchiveBean.siteSyllabi}"
					var="entry"
					headerClass="headerAlignment"
					columnClasses="deleteCol,titleCol"
					styleClass="listHier">
					<h:column>
						<f:facet name="header">
							<h:outputText value="Archive?"/>
						</f:facet>
						<h:selectBooleanCheckbox id="itemSelect" value="#{entry.selected}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Title"/>
						</f:facet>
						<h:outputText value="#{entry.item.title}"/>
					</h:column>
				</h:dataTable>

				<sakai:button_bar>
					<h:commandButton styleClass="active" accesskey="s" value="Archive Selected" action="#{CourseArchiveBean.processActionArchiveSyllabi}"/>
					<h:commandButton accesskey="x" value="#{msgs.cancel}" action="#{CourseArchiveBean.processActionShow}"/>
				</sakai:button_bar>
			</h:form>
 		</sakai:view_content>
	</sakai:view_container>
</f:view>
