<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="addUpdateItem">
				<sakai:view_title value="#{msgs.item_add_page_title}"/>

				<sakai:messages />

				<sakai:panel_edit>
					<h:outputText value="Course Code"/>
					<h:selectOneMenu value="#{CourseArchiveBean.itemSite}" required="true">
						<f:selectItems value="#{CourseArchiveBean.currentUserSites}"/>
					</h:selectOneMenu>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Primary Instructor"/>
					<h:inputText value="#{CourseArchiveBean.itemInstructor}"/>
				</sakai:panel_edit>

				<sakai:button_bar>
					<h:commandButton accesskey="s" styleClass="active" value="#{msgs.save_button}" action="#{CourseArchiveBean.processActionAdd}"/>
					<h:commandButton accesskey="x" value="#{msgs.cancel_button}" action="#{CourseArchiveBean.processActionList}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
