<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.list_items}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="addUpdateSyllabus" enctype="multipart/form-data">
				<sakai:view_title value="Edit Syllabus"/>

				<sakai:messages/>

				<sakai:panel_edit>
					<h:outputText value="Title"/>
					<h:inputText value="#{CourseArchiveBean.currentSyllabus.title}"/>

					<h:outputText value="Content"/>
					<h:inputTextarea rows="20" cols="80" value="#{CourseArchiveBean.currentSyllabus.asset}"/>
				</sakai:panel_edit>

				<sakai:view_title value="Attachments"/>

				<sakai:panel_edit>
					<h:outputText value="Filename"/>
					<sakai:inputFileUpload valueChangeListener="#{CourseArchiveBean.processUpload}" />
				</sakai:panel_edit>

				<sakai:button_bar>
					<h:commandButton styleClass="active" accesskey="s" value="#{msgs.save}" action="#{CourseArchiveBean.processActionSaveSyllabus}"/>
					<h:commandButton accesskey="x" value="#{msgs.cancel}" action="#{CourseArchiveBean.processActionShow}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
