<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionShow}" value="Back to Course"/>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form>
				<sakai:view_title value="Class Roster for #{CourseArchiveBean.itemCode}-#{CourseArchiveBean.itemTerm}"/>

				<h:dataTable
					value="#{CourseArchiveBean.itemStudents}"
					var="student"
					headerClass="headerAlignment"
					styleClass="listHier">
					<h:column>
						<f:facet name="header">
							<h:outputText value="ID"/>
						</f:facet>
						<h:outputText value="#{student.sid}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Name"/>
						</f:facet>
						<h:outputText value="#{student.name}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="Email"/>
						</f:facet>
						<h:outputLink value="mailto:#{student.email}">
							<h:outputText value="#{student.email}"/>
						</h:outputLink>
					</h:column>
				</h:dataTable>

				<sakai:button_bar>
					<h:commandButton value="#{msgs.edit_button}" action="#{CourseArchiveBean.processActionUpdate}" rendered="#{CourseArchiveBean.itemCanEdit}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
