<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}" />
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="addUpdateItem">
			 	<sakai:view_title value="#{msgs.item_edit_page_title}"/>

				<sakai:messages />

				<sakai:panel_edit>
					<h:outputText value="Course Name"/>
					<h:inputText value="#{CourseArchiveBean.itemText}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Primary Instructor"/>
					<h:inputText value="#{CourseArchiveBean.itemInstructor}"/>
				</sakai:panel_edit>

				<sakai:panel_edit>
					<h:outputText value="Enrollment"/>
					<h:inputText value="#{CourseArchiveBean.itemEnrollment}"/>
				</sakai:panel_edit>

				<sakai:button_bar>
					<h:commandButton value="#{msgs.save_button}" action="#{CourseArchiveBean.processActionAdd}" /> 
					<h:commandButton value="#{msgs.cancel_button}" action="#{CourseArchiveBean.processActionShow}" /> 
                </sakai:button_bar>

			 </h:form>
  		</sakai:view_content>	
	</sakai:view_container>
</f:view> 
