<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="CourseArchive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="search">
			<sakai:tool_bar>
				<h:inputText value="#{CourseArchiveBean.searchQuery}"/>
				<h:commandButton value="#{msgs.search}" action="#{CourseArchiveBean.processActionSearch}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="items">
				<sakai:view_title value="#{msgs.list_title}"/>

				<sakai:messages />

				<h:dataTable
					value="#{CourseArchiveBean.items}"
					var="entry"
					columnClasses="checkCol,codeCol,nameCol,instructorCol,enrollmentCol,publicCol,dateCol"
					headerClass="headerAlignment"
					styleClass="listHier">

					<h:column rendered="#{CourseArchiveBean.userCanDeleteItems}">
						<f:facet name="header">
							<h:outputText value=""/>
						</f:facet>
						<h:selectBooleanCheckbox id="itemSelect" value="#{entry.selected}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_code}"/>
						</f:facet>
						<h:commandLink id="showlink" action="#{CourseArchiveBean.processActionShow}">
							<h:outputText value="#{entry.item.title}"/>
						</h:commandLink>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_name}"/>
						</f:facet>
						<h:outputText value="#{entry.item.name}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_primary_instructor}"/>
						</f:facet>
						<h:outputText value="#{entry.item.primaryInstructor}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_enrollment}"/>
						</f:facet>
						<h:outputText value="#{entry.item.enrollment}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_public}"/>
						</f:facet>
						<h:outputText value="#{entry.item.public}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.item_date_created}"/>
						</f:facet>
						<h:outputText value="#{entry.item.dateCreated}">
							<f:convertDateTime type="both" dateStyle="medium" timeStyle="short"/>
						</h:outputText>
					</h:column>
				</h:dataTable>

				<sakai:button_bar>
					<sakai:button_bar_item action="#{CourseArchiveBean.processActionShowOlder}" value="Reveal Older Items" rendered="#{CourseArchiveBean.hasMore}"/>
					<sakai:button_bar_item action="#{CourseArchiveBean.processActionMerge}" value="#{msgs.merge}" rendered="#{CourseArchiveBean.userCanDeleteItems}"/>
					<sakai:button_bar_item action="#{CourseArchiveBean.processActionDelete}" value="#{msgs.delete}" rendered="#{CourseArchiveBean.userCanDeleteItems}"/>
				</sakai:button_bar>
			</h:form>
		</sakai:view_content>
	</sakai:view_container>
</f:view>
