<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.project_list_items_link}" />
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="addUpdateItem">
			 	<sakai:view_title value="#{msgs.item_add_page_title}"/>

				<sakai:messages />

				<sakai:instruction_message value="Hello, #{CourseArchiveBean.currentUserDisplayName}"/>

				<sakai:panel_edit>
					<h:outputText value="Course"/>
					<h:selectOneMenu required="true">
						<f:selectItems value="#{CourseArchiveBean.currentUserSites}"/>
					</h:selectOneMenu>
				</sakai:panel_edit>

			 	<sakai:panel_edit>
				 	<h:outputText value="#{msgs.item_add_hidden}"/>
				 	<h:selectBooleanCheckbox title="#{msgs.item_add_hidden_tooltip}" 
				 		value="#{CourseArchiveBean.itemHidden}">
					</h:selectBooleanCheckbox>
			 	</sakai:panel_edit>

				<sakai:button_bar>
					<h:commandButton value="#{msgs.item_add_add_button}" action="#{CourseArchiveBean.processActionAdd}" /> 
                </sakai:button_bar>

			 </h:form>
  		</sakai:view_content>	
	</sakai:view_container>
</f:view> 
