<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Course Archive Tool">
		<style type="text/css">
			@import url("/coursearchive-tool/css/CourseArchive.css");
		</style>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionShow}" value="#{msgs.back_to_course}"/>
				<sakai:tool_bar_item action="#{CourseArchiveBean.processActionList}" value="#{msgs.list_items}"/>
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<sakai:view_title value="#{CourseArchiveBean.currentSyllabus.title}"/>

			<h:outputText value="#{CourseArchiveBean.currentSyllabus.asset}" escape="false"/>

			<sakai:view_title value="Attachments"/>

			<h:dataTable
				value="#{CourseArchiveBean.syllabusAttachments}"
				var="entry"
				headerClass="headerAlignment"
				styleClass="listHier">
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msgs.attachment_name}"/>
					</f:facet>
					<h:outputLink value="#{entry.resourceURL}">
						<h:outputText value="#{entry.name}"/>
					</h:outputLink>
				</h:column>
			</h:dataTable>

		</sakai:view_content>
	</sakai:view_container>
</f:view>
